In [140]:
import torch
torch.__version__

'2.9.1+cpu'

# Linear Regression

In [167]:
import numpy as np
import matplotlib.pyplot as plt

In [168]:
# regression formula -> y = mx + c

weight = 0.7
bias = 0.3

x = torch.arange(0,1,0.02).reshape(-1, 1)
y = weight * x + bias

In [169]:
x[:5], y[:5]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560]]))

In [170]:
len(x), len(y)

(50, 50)

In [171]:
x.shape, x.ndim

(torch.Size([50, 1]), 2)

In [172]:

X_train = x[:40]
X_test = x[40:]
y_train = y[:40]
y_test = y[40:]

In [173]:
len(X_train), len(X_test)

(40, 10)

In [174]:
X_train[0], y_train[0]

(tensor([0.]), tensor([0.3000]))

In [175]:
from torch import nn

In [176]:
class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)
    def forward(self, x):
        return self.linear(x)

In [177]:
model = LinearModel()

In [178]:
model

LinearModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [179]:
with torch.inference_mode():
    pred = model(X_train[0])

pred

tensor([0.6726])

In [180]:
from torch.nn import L1Loss
from torch.optim import SGD

In [181]:
criterion = L1Loss()
optimizer = SGD(params=model.parameters(), lr=0.01)

In [182]:
from tqdm import tqdm

In [191]:
epochs = 1000

for epoch in tqdm(range(epochs)):
    model.train()
    pred = model(X_train)
    loss = criterion(pred, y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"__Epoch__:{epoch}\n")
        print(f"LOSS:{loss:.5f}\n")

 12%|█▏        | 121/1000 [00:00<00:00, 1208.85it/s]

__Epoch__:0

LOSS:0.03959

__Epoch__:100

LOSS:0.00525



 31%|███       | 307/1000 [00:00<00:01, 394.85it/s] 

__Epoch__:200

LOSS:0.00445

__Epoch__:300

LOSS:0.00445



 66%|██████▌   | 655/1000 [00:00<00:00, 928.95it/s]

__Epoch__:400

LOSS:0.00445

__Epoch__:500

LOSS:0.00445

__Epoch__:600

LOSS:0.00445

__Epoch__:700

LOSS:0.00445



100%|██████████| 1000/1000 [00:01<00:00, 874.15it/s]

__Epoch__:800

LOSS:0.00445

__Epoch__:900

LOSS:0.00445



In [192]:
X_test[0], y_test[0]

(tensor([0.8000]), tensor([0.8600]))

In [193]:
with torch.inference_mode():
    y_pred = model(X_test[0])

y_pred

tensor([0.8529])