<a href="https://colab.research.google.com/github/mszhdgr/Machine_learning/blob/Main/Recommendors/Recommendor_sys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import warnings

warnings.filterwarnings("ignore")

In [28]:
import kagglehub

path = kagglehub.dataset_download("harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'imdb-dataset-of-top-1000-movies-and-tv-shows' dataset.
Path to dataset files: /kaggle/input/imdb-dataset-of-top-1000-movies-and-tv-shows


In [29]:
import pandas as pd

df = pd.read_csv("/kaggle/input/imdb-dataset-of-top-1000-movies-and-tv-shows/imdb_top_1000.csv")
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"


In [30]:
df.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

In [31]:
data = pd.DataFrame(df, columns=['IMDB_Rating','Genre','Series_Title','Overview'])
data.head()

,IMDB_Rating,Genre,Series_Title,Overview
0,9.3,Drama,The Shawshank Redemption,Two imprisoned men bond over a number of years...
1,9.2,"Crime, Drama",The Godfather,An organized crime dynasty's aging patriarch t...
2,9.0,"Action, Crime, Drama",The Dark Knight,When the menace known as the Joker wreaks havo...
3,9.0,"Crime, Drama",The Godfather: Part II,The early life and career of Vito Corleone in ...
4,9.0,"Crime, Drama",12 Angry Men,A jury holdout attempts to prevent a miscarria...


In [32]:
data.isna().sum()

,0
IMDB_Rating,0
Genre,0
Series_Title,0
Overview,0


In [33]:
data['Overview']

,Overview
0,Two imprisoned men bond over a number of years...
1,An organized crime dynasty's aging patriarch t...
2,When the menace known as the Joker wreaks havo...
3,The early life and career of Vito Corleone in ...
4,A jury holdout attempts to prevent a miscarria...
...,...
995,A young New York socialite becomes interested ...
996,Sprawling epic covering the life of a Texas ca...
997,"In Hawaii in 1941, a private is cruelly punish..."
998,Several survivors of a torpedoed merchant ship...


In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfid = TfidfVectorizer()
tfid_vect = tfid.fit_transform(data['Overview'])

In [35]:
tfid_vect

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 21677 stored elements and shape (1000, 5648)>

In [36]:
tfid.get_feature_names_out()

array(['00', '000', '007', ..., 'zuckerberg', 'zulu', 'édith'],
      dtype=object)

In [37]:
tfid_vect.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [39]:
indices = pd.Series(df.index, df['Series_Title'])
indices

,0
Series_Title,
The Shawshank Redemption,0
The Godfather,1
The Dark Knight,2
The Godfather: Part II,3
12 Angry Men,4
...,...
Breakfast at Tiffany's,995
Giant,996
From Here to Eternity,997


In [40]:
data[data['Series_Title'] == 'Giant']

,IMDB_Rating,Genre,Series_Title,Overview
996,7.6,"Drama, Western",Giant,Sprawling epic covering the life of a Texas ca...


In [41]:
indices['Giant']

np.int64(996)

In [42]:
from sklearn.metrics.pairwise import cosine_similarity

cos_sim = cosine_similarity(tfid_vect, tfid_vect)

In [43]:
cos_sim

array([[1.        , 0.01006088, 0.03008628, ..., 0.00438177, 0.0239373 ,
        0.00742112],
       [0.01006088, 1.        , 0.0279293 , ..., 0.02788541, 0.01268451,
        0.01073063],
       [0.03008628, 0.0279293 , 1.        , ..., 0.02747128, 0.076111  ,
        0.08355256],
       ...,
       [0.00438177, 0.02788541, 0.02747128, ..., 1.        , 0.0360289 ,
        0.048581  ],
       [0.0239373 , 0.01268451, 0.076111  , ..., 0.0360289 , 1.        ,
        0.02835585],
       [0.00742112, 0.01073063, 0.08355256, ..., 0.048581  , 0.02835585,
        1.        ]])

In [45]:
movie_idx = indices['The Godfather']
movie_idx

np.int64(1)

In [51]:
sim_scores = cos_sim[movie_idx]
sim_scores[:5]

array([0.01006088, 1.        , 0.0279293 , 0.10335163, 0.03147044])

In [54]:
similarity_scores = pd.DataFrame(sim_scores, columns=['Scores'])
similarity_scores

,Scores
0,0.010061
1,1.000000
2,0.027929
3,0.103352
4,0.031470
...,...
995,0.004804
996,0.025299
997,0.027885
998,0.012685


In [65]:
movie_indexes = similarity_scores.sort_values('Scores', ascending=False)[1:11].index
movie_indexes

Index([463, 974, 184, 739, 88, 26, 3, 913, 307, 569], dtype='int64')

In [66]:
data['Series_Title'].iloc[movie_indexes]

,Series_Title
463,Knives Out
974,The Godfather: Part III
184,Smultronstället
739,Nebraska
88,Jagten
26,La vita è bella
3,The Godfather: Part II
913,Die Welle
307,Ace in the Hole
569,The Gentlemen


In [72]:
mv_idx = indices['Gladiator']
mv_idx

np.int64(39)

In [73]:
glad_simscore = cos_sim[mv_idx]
glad_simscore[:5]

array([0.00526941, 0.02184673, 0.03041237, 0.05521379, 0.02217301])

In [74]:
glad_sim_score = pd.DataFrame(glad_simscore, columns=['Scores'])
glad_sim_score

,Scores
0,0.005269
1,0.021847
2,0.030412
3,0.055214
4,0.022173
...,...
995,0.052102
996,0.061709
997,0.018646
998,0.009812


In [75]:
gladiator_idx = glad_sim_score.sort_values('Scores', ascending=False)[1:11].index
gladiator_idx

Index([300, 782, 831, 369, 549, 177, 241, 238, 642, 242], dtype='int64')

In [76]:
data['Series_Title'][gladiator_idx]

,Series_Title
300,Ben-Hur
782,Man on Fire
831,The Last Emperor
369,Kill Bill: Vol. 2
549,Spartacus
177,Sholay
241,Kill Bill: Vol. 1
238,Munna Bhai M.B.B.S.
642,The Count of Monte Cristo
242,Finding Nemo
