## Area of a Circle

- formulae is pi * r^2

In [119]:
PI = 3.14

In [120]:
PI

3.14

In [121]:
import numpy as np

r = np.array(range(0, 1000, 2)).reshape(-1, 1)
r[:5]

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [122]:
len(r)

500

In [123]:
np.pow(2, 2)

np.int32(4)

In [124]:
squares = [np.pow(i, 2).item() for i in r]
squares[:5]

[0, 4, 16, 36, 64]

In [125]:
y = [PI * i for i in squares]
y[:5]

[0.0, 12.56, 50.24, 113.04, 200.96]

In [126]:
type(y)

list

In [127]:
y = np.array(y)
type(y)

numpy.ndarray

In [128]:
from sklearn.linear_model import LinearRegression

In [129]:
model = LinearRegression()

In [130]:
model

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [131]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(r, y, test_size=0.3)

In [132]:
len(X_train), len(X_test)

(350, 150)

In [133]:
model.fit(X_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [134]:
model.score(X_test, y_test)

0.9298286994293915

In [135]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

preds = model.predict(X_test)
R2 = r2_score(y_test, preds)
MAE = mean_absolute_error(y_test, preds)
MSE = mean_squared_error(y_test, preds)

print(f"R2: {R2}")
print(f"MAE: {MAE}")
print(f"MSE: {MSE}")

R2: 0.9298286994293915
MAE: 211353.29028727257
MSE: 59144405110.0791


## Deep learning regression recap

In [136]:
import torch
torch.__version__

'2.5.1'

In [137]:
from torch import nn

In [138]:
class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)
    def forward(self, x):
        return self.linear(x)

In [157]:
model1 = SimpleNN()
model1

SimpleNN(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [159]:
x = torch.arange(0, 100, 0.02).reshape(-1, 1)
m = 0.7
c = 0.3
y = m * x + c

In [160]:
x[:3],y[:3]

(tensor([[0.0000],
         [0.0200],
         [0.0400]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280]]))

In [161]:
len(x), len(y)

(5000, 5000)

In [162]:
X_train, X_test, y_train, y_test= x[:400], x[400:], y[:400], y[400:]


In [163]:
len(X_train), len(X_test)

(400, 4600)

In [164]:
X_test[:4]

tensor([[8.0000],
        [8.0200],
        [8.0400],
        [8.0600]])

In [165]:
with torch.inference_mode():
    pred = model_1(X_train[0].float())

pred

tensor([-0.4998])

In [166]:
from torch.nn import L1Loss
from torch.optim import SGD

criterion = L1Loss()
optimizer = SGD(params=model_1.parameters(), lr=0.1)

In [167]:
for epoch in range(1000):
    model_1.train()
    pred = model_1(X_train.float())
    loss = criterion(y_train, pred)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"__Epoch__: {epoch}\n")
        print(f"Loss__: {loss:.5f}")

__Epoch__: 0

Loss__: 5.00643
__Epoch__: 100

Loss__: 0.17321
__Epoch__: 200

Loss__: 0.15843
__Epoch__: 300

Loss__: 0.15843
__Epoch__: 400

Loss__: 0.15843
__Epoch__: 500

Loss__: 0.15843
__Epoch__: 600

Loss__: 0.15843
__Epoch__: 700

Loss__: 0.15843
__Epoch__: 800

Loss__: 0.15843
__Epoch__: 900

Loss__: 0.15843


In [168]:
X_test[0], y_test[0]

(tensor([8.]), tensor([5.9000]))

In [169]:
with torch.inference_mode():
    pred = model_1(X_test[0].float())

pred

tensor([5.6826])