<a href="https://colab.research.google.com/github/mszhdgr/Machine_learning/blob/Main/Linear%20Regression/House_Price_Sirilanka.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import warnings

warnings.filterwarnings("ignore")

In [49]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nishanobeysekera/house-prices")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'house-prices' dataset.
Path to dataset files: /kaggle/input/house-prices


In [50]:
import pandas as pd

df = pd.read_csv("/kaggle/input/house-prices/house_prices_srilanka.csv")
df.head()

,SquareFootage,Bedrooms,Location,Price
0,1660,2,Suburb,166100000
1,2094,4,Suburb,209600000
2,1930,2,Rural,193100000
3,1895,5,Suburb,189750000
4,2438,4,Rural,244000000


In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23456 entries, 0 to 23455
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   SquareFootage  23456 non-null  int64 
 1   Bedrooms       23456 non-null  int64 
 2   Location       23456 non-null  object
 3   Price          23456 non-null  int64 
dtypes: int64(3), object(1)
memory usage: 733.1+ KB


In [52]:
df['Location'].unique()

array(['Suburb', 'Rural', 'Urban'], dtype=object)

In [53]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoded_location = encoder.fit_transform(df['Location'])

In [54]:
encoded_location

array([1, 1, 0, ..., 1, 2, 2])

In [55]:
df['Encoded_Location'] = encoded_location
df.head()

,SquareFootage,Bedrooms,Location,Price,Encoded_Location
0,1660,2,Suburb,166100000,1
1,2094,4,Suburb,209600000,1
2,1930,2,Rural,193100000,0
3,1895,5,Suburb,189750000,1
4,2438,4,Rural,244000000,0


In [56]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
sf_encoded = scaler.fit_transform(df['SquareFootage'].values.reshape(-1,1))
df['sq_encoded'] = sf_encoded
df.head()

,SquareFootage,Bedrooms,Location,Price,Encoded_Location,sq_encoded
0,1660,2,Suburb,166100000,1,-0.391235
1,2094,4,Suburb,209600000,1,0.296513
2,1930,2,Rural,193100000,0,0.036627
3,1895,5,Suburb,189750000,1,-0.018837
4,2438,4,Rural,244000000,0,0.841641


In [57]:
featurez = ['Bedrooms','sq_encoded','Encoded_Location']
labels = ['Price']
x = pd.DataFrame(df, columns=featurez)
y = pd.DataFrame(df, columns=labels)
x.head()

,Bedrooms,sq_encoded,Encoded_Location
0,2,-0.391235,1
1,4,0.296513,1
2,2,0.036627,0
3,5,-0.018837,1
4,4,0.841641,0


In [58]:
y.tail()

,Price
23451,89350000
23452,231600000
23453,192750000
23454,131300000
23455,232900000


In [61]:
y = y.values.ravel()
y

array([166100000, 209600000, 193100000, ..., 192750000, 131300000,
       232900000])

In [62]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
len(X_train), len(X_test)

(18764, 4692)

In [63]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [64]:
model.score(X_test, y_test)

0.9999433433569386

In [65]:
from sklearn.metrics import r2_score

pred = model.predict(X_test)
r2 = r2_score(y_test, pred)
r2

0.9999433433569386

In [66]:
model.feature_names_in_

array(['Bedrooms', 'sq_encoded', 'Encoded_Location'], dtype=object)

In [70]:
test_in = [[1,700,0],[2, 1600, 1], [5, 4800, 2]]
test_df = pd.DataFrame(test_in, columns=model.feature_names_in_)
test_df

,Bedrooms,sq_encoded,Encoded_Location
0,1,700,0
1,2,1600,1
2,5,4800,2


In [76]:
test_df['sq_encoded'] = scaler.transform(test_df[['sq_encoded']])
test_df

,Bedrooms,sq_encoded,Encoded_Location
0,1,-1.912522,0
1,2,-0.486316,1
2,5,4.584641,2


In [77]:
predictions = model.predict(test_df)

In [78]:
predictions

array([6.97053873e+07, 1.60760772e+08, 4.81923893e+08])

In [79]:
import numpy as np

pd.set_option('display.float_format', lambda x: '%.2f' % x)
predictions_df = pd.DataFrame(predictions, columns=['Predicted Price'])
display(predictions_df)

,Predicted Price
0,69705387.30
1,160760772.24
2,481923893.48
